# coding: utf-8

import sys
import os
import datetime

from Chapter import Chapter

class Book:
	"""etxt 图书对象"""
	def __init__(self, prog="etxt_maker"):
		self.name     = ""
		self.author   = ""
		self.prog = prog
		self.chapters = []

	def load(self, filename):
		f = open(filename, 'r')
		lines = f.readlines()
		f.close()
		currentChapter = 0;
		for line in lines:
			if line.startswith("<"):
				self.name = line[1:].strip()
				continue
			if line.startswith("@"):
				self.author = line[1:].strip()
				continue
			if line.startswith("#"):
				if currentChapter:
					self.chapters.append(currentChapter)
				currentChapter = Chapter()
				currentChapter.name = line[1:].strip()
				continue
			if line.startswith("!"):
				continue
			if len(line.strip()):
				if currentChapter:
					currentChapter.paragraphs.append(line.strip())
		if currentChapter:
			self.chapters.append(currentChapter)

	def info(self):
		print("")
		print("书名: %s" % self.name)
		print("作者: %s" % self.author)
		print("章节: %d章" % len(self.chapters))
		print("")
		if __name__ == "__main__":
			print("=================")
			for c in self.chapters:
				print(" = %s" % c.name)
			print("=================")
	
	def dumpTo(self, dirname):
		"""将本书导出到指定目录"""
		if not os.path.isdir(dirname):
			os.mkdir(dirname)
		
		
		indexfile = open("%s/index.html" % dirname, 'w')
		
		indexfile.writelines("<html>\n")
		indexfile.writelines("<head>\n")
		indexfile.writelines("<title>%s</title>\n" % self.name)
		indexfile.writelines("""<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />\n""")
		indexfile.writelines("</head>\n")
		indexfile.writelines("<body>\n")
		indexfile.writelines("<h1>《%s》</h1>" % self.name)
		indexfile.writelines("<p>作者：%s</p>" % self.author)
		indexfile.writelines("<ol>\n")
		
		index=1
		pre=0
		nxt=index+1
		
		for chapter in self.chapters:
			indexfile.writelines("""  <li><a href="%d.html">%s</a></li>\n""" % (index, chapter.name))
			chapter.dumpTo(dirname, pre, index, nxt, len(self.chapters))
			index+=1;
			pre = index - 1
			nxt = index + 1
		
		indexfile.writelines("</ol>\n")
		indexfile.writelines("<p>Generated by %s. %s</p>\n"
					% (self.prog, datetime.datetime.strftime(datetime.datetime.now(), "%Y-%m-%d %T")))
		indexfile.writelines("</body>\n")
		indexfile.writelines("</html>")
		
		indexfile.close()

if __name__ == "__main__":
	book = Book()
	book.load("/home/yaoms/books/gcd/1.etxt")
	book.info()
