# coding: utf-8
from optparse import OptionParser
from utils.confirm_ask import confirm_ask
from etxt.Book import Book, Chapter

import re
import os
import sys
import datetime

version = "%prog 1.0"
usage="\n\n  %prog -f eletxtbookname.etxt -d outputdir"

parser = OptionParser(usage=usage, version=version)
parser.add_option("-f", "--file", dest="filename",
                      help="read etxt from FILENAME.")
parser.add_option("-d", "--dir", dest="dirname",
                      help="output html to this DIRNAME.")
(options, args) = parser.parse_args()

if not options.filename or not options.dirname:
    parser.print_help()
    sys.exit(1)

f = open(options.filename,'r')
lines = f.readlines()

f.close()

book = Book()
book.load(lines)

#提问一些简单的信息，例如书的分类
book.info()
#for chapter in chapters[:3]:
#    print chapter['title']
#    print "-----------------------"
#    print chapter['content']
#    print "-----------------------"
##!!!!!
#sys.exit(0)

if not confirm_ask("是否确认继续？"):
    print "exit"
    sys.exit(0)


if not os.path.isdir(options.dirname):
	os.mkdir(options.dirname)

indexfile = open("%s/index.html" % options.dirname, 'w')

indexfile.writelines("""<html>
<head>
<title>%s</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
</head>
<body>
<h1>《%s》</h1>
<p>作者：%s</p>
<ol>
""" % (book.name, book.name, book.author))

index=1
pre=0
nxt=index+1

for chapter in book.chapters:
	indexfile.writelines("""  <li><a href="%d.html">%s</a></li>\n""" % (index, chapter.title))
	this_chapter_file=open("%s/%d.html" % (options.dirname, index), 'w')
	this_chapter_file.writelines("""<html>
<head>
<title>%s</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<style>
p {text-indent:2em;}
</style>
</head>
<body>
<h1>%s</h1>
""" % (chapter.title, chapter.title))

	for p in chapter.content:
		this_chapter_file.writelines("""<p>%s</p>\n""" % p)
	
	this_chapter_file.writelines("<hr/>\n")
	this_chapter_file.writelines("<p>")
	if pre >= 1:
		this_chapter_file.writelines("""<a href="%d.html" title="prev">上一章</a>\n""" % pre)
	this_chapter_file.writelines("""<a href="index.html" title="home">返回目录</a>\n""")
	if nxt <= len(book.chapters):
		this_chapter_file.writelines("""<a href="%d.html" title="next">下一章</a>\n""" % nxt)
	this_chapter_file.writelines("</p>\n")

	this_chapter_file.writelines("""</body>
</html>""")
	this_chapter_file.close()
	index+=1;
	pre = index - 1
	nxt = index + 1

indexfile.writelines("""</ol>
<p>Generated by from_etxt_to_html.py by yaoms. %s</p>
</body>
</html>""" % datetime.datetime.strftime(datetime.datetime.now(), "%Y-%m-%d %T"))

indexfile.close()
